# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reproProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reproProject
  pod 'MobileCenter/Crashes', '~> 0.11.2'
  pod 'RNMobileCenterShared', '~> 0.8.1'
  pod 'MobileCenter/Analytics', '~> 0.11.2'

  

  target 'reproProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reproProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reproProject-tvOS

  target 'reproProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
